# Generated by Django 5.1.6 on 2025-02-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='model',
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.CharField(max_length=1002),
        ),
    ]
